[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[nixpacks]
output-dir = "./nixpacks-output"

# Přidejte tuto sekci pro vyloučení tsconfig.tsbuildinfo z cache
[phases.build.cache]
exclude = ["tsconfig.tsbuildinfo"]
